name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/native-scanner
          api_endpoint: https://api.dev.boostsec.io

      - name: Checkov Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/checkov
          api_endpoint: https://api.dev.boostsec.io

      - name: Checkov Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/checkov
          api_endpoint: https://api.dev.boostsec.io

      - name: Checkov Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/checkov
          api_endpoint: https://api.dev.boostsec.io

      - name: Semgrep Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/semgrep
          api_endpoint: https://api.dev.boostsec.io

      - name: Snyk Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/snyk-test
          api_endpoint: https://api.dev.boostsec.io
